# This is a basic workflow to help you get started with Actions

name: Create Comment when Openning Issues

# Controls when the workflow will run
on:
  issues:
    types: [ opened ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment-with-action:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Dump Github Context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

      
